#!/usr/bin/env bash
# This script installs nginx on a web server 
# sets it's default respone to a file contianing Hello world!

rule="\n\terror_page 404 /404.html;\n\n\tlocation /redirect_me {\n\t\treturn 404"

apt-get -y update;
apt-get -y install nginx;
ufw allow 'Nginx HTTP';
echo "Hello World!" >> /var/www/html/index.html
sed -i "/server_name _;/a \\$rule" /etc/nginx/sites-available/default
service nginx start
