#!/usr/bin/env bash
# A script that read and formats the /etc/passwd data

while IFS=: read -r usrName pass uid gid uidinfo dir shell _;
do
	echo "The user ${usrName} is part of the ${gid} gang,\
lives in ${dir} and rides ${shell}. ${uid}'s place\
protected by the passcode ${pass}, more info about\
the user here: ${uidinfo}"

done < /etc/passwd
