#!/usr/bin/env bash
# a Bash script that displays the visitor IP along
# with the HTTP status code from the Apache log file.

awk 'match($0, /([0-9]{1,3}\.){3}[0-9]{1,3}/) {
	ip = substr($0, RSTART, RLENGTH); 
	}
	match($0, /HTTP\/[0-9]\.[0-9]" [1-5][0-9]{2}/) {
		http_code = substr($0, RSTART+10, 3);
		printf "%s %s\n", ip, http_code
	}' apache_access.log
